version: '3.5'
services:
  mintos.weathertask:
    build: ./
    image: streamline27/mintos.weathertask:latest
    container_name: mintos.weathertask
    ports:
      - "8190:8080"
    environment:
      - "spring.profiles.active=docker"
#    volumes:
#      - "/Users/Vladislav/Development/Home/Kotlin/logs:/logs"